# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.CharField(max_length=200)),
                ('Nombres', models.TextField(max_length=200)),
                ('Apellido_p', models.TextField(max_length=200)),
                ('Apellido_m', models.TextField(max_length=200)),
                ('Escuela', models.TextField(max_length=200)),
                ('Curso', models.TextField(max_length=200)),
                ('Puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Slug', models.SlugField(blank=True)),
            ],
        ),
    ]
