# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20170529_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='Slug',
        ),
    ]
