# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_alumnos_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='Puntuacion',
            new_name='Calificacion',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='Apellido_m',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='Apellido_p',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='Nombres',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='Nombre',
            field=models.CharField(default='97', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Escuela',
            field=models.CharField(max_length=200),
        ),
    ]
