# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20170529_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='Contra',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Calificacion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
