# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_auto_20170530_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
