# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_auto_20170530_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
