# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_auto_20170530_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
